# Generated by Django 5.0.6 on 2024-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='assets/img/icons/weather-sm.jpg', null=True, upload_to='user/'),
        ),
    ]
